version: "3.9"  # optional since v1.27.0
services:
  eureka-server:
    build: ./Eureka-Server
    environment:
      - server.port=50000
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "50000:50000"
  zuul-server:
    build: ./zuul-server
    environment:
      - server.port=8762
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
    ports:
      - "8762:8762"
  config-server:
    build: ./Config-Server
    environment:
      - server.port=8888
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
    ports:
      - "8888:8888"
  product-service:
    build: ./Product
    environment:
      - server.port=5000
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "5000:5000"
  #product-service2:
    #build: ./Product
    #environment:
    #  - server.port=5001
    #  - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
    #  - spring.cloud.config.uri=http://config-server:8888
    #  - spring.config.import=optional:configserver:http://config-server:8888/
    #ports:
    #  - "5001:5001"
  user-service:
    build: ./User
    environment:
      - server.port=40000
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "40000:40000"
  evenement-service:
    build: ./ECommerceMS
    environment:
      - server.port=9000
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "9000:9000"
  commande-service:
    build: ./Commande
    environment:
      - server.port=7700
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "7700:7700"
  wishlist-service:
    build: ./Wishlist
    environment:
      - server.port=20000
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:50000/eureka/
      - spring.cloud.config.uri=http://config-server:8888
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "20000:20000"
    depends_on:
      - eureka-server
      